import type { HexColor, Rune, RunePixel } from './types';

const PIXEL_RUNE_BACKGROUND = '#101018';

function pixelsFromRows(rows: readonly string[], palette: Record<string, HexColor>): RunePixel[] {
  return rows.flatMap((row, y) =>
    Array.from(row).flatMap((symbol, x) => {
      const color = palette[symbol];

      return color ? [{ x, y, color }] : [];
    }),
  );
}

export const defaultRunes = [
  {
    id: 'heart-default',
    name: 'Heart',
    width: 16,
    height: 16,
    backgroundColor: PIXEL_RUNE_BACKGROUND,
    pixels: pixelsFromRows(
      [
        '................',
        '................',
        '................',
        '....RR....RR....',
        '...RLLR..RLLR...',
        '..RLLLLRRLLLLR..',
        '..RLLLLLLLLLLR..',
        '..RLLLLLLLLLLR..',
        '...RLLLLLLLLR...',
        '....RLLLLLLR....',
        '.....RLLLLR.....',
        '......RLLR......',
        '.......RR.......',
        '................',
        '................',
        '................',
      ],
      {
        L: '#FF7AAF',
        R: '#FF4D8D',
      },
    ),
  },
  {
    id: 'moon-default',
    name: 'Moon',
    width: 16,
    height: 16,
    backgroundColor: '#0D1324',
    pixels: pixelsFromRows(
      [
        '................',
        '..........S.....',
        '.......MMMM.....',
        '.....MMLLMM.....',
        '....MLLLM.......',
        '...MLLLM........',
        '...MLLLM....S...',
        '..MLLLLM........',
        '..MLLLLM........',
        '...MLLLM........',
        '...MLLLLM.......',
        '....MLLLMM......',
        '.....MMLLMMM....',
        '.......MMMM.....',
        '..........S.....',
        '................',
      ],
      {
        L: '#FFF4C8',
        M: '#F8E8A0',
        S: '#8BA7FF',
      },
    ),
  },
  {
    id: 'spark-default',
    name: 'Spark',
    width: 16,
    height: 16,
    backgroundColor: '#11111A',
    pixels: pixelsFromRows(
      [
        '................',
        '.......YY.......',
        '.......LL.......',
        '......YWWY......',
        '......LWWL......',
        '.....YWWWWY.....',
        '..OYLLWWWWLLYO..',
        '.OYLLWWWWWWLLYO.',
        '.OYLLWWWWWWLLYO.',
        '..OYLLWWWWLLYO..',
        '.....YWWWWY.....',
        '......LWWL......',
        '......YWWY......',
        '.......LL.......',
        '.......YY.......',
        '................',
      ],
      {
        L: '#FFF5A8',
        O: '#FFB347',
        W: '#FFFFFF',
        Y: '#FFE66D',
      },
    ),
  },
  {
    id: 'guardian-16-default',
    name: 'Guardian 16',
    width: 16,
    height: 16,
    backgroundColor: '#080A14',
    pixels: pixelsFromRows(
      [
        '................',
        '......PPPP......',
        '.....PCCCCP.....',
        '....PCLLLLCP....',
        '...PCLPPPPCLP...',
        '..PCLP....PLCP..',
        '.PCLP..LL..PLCP.',
        'PCLP..LCCL..PLCP',
        'PCLP..LCCL..PLCP',
        '.PCLP..LL..PLCP.',
        '..PCLP....PLCP..',
        '...PCLPPPPCLP...',
        '....PCLLLLCP....',
        '.....PCCCCP.....',
        '......PPPP......',
        '................',
      ],
      {
        C: '#61F2FF',
        L: '#D6FBFF',
        P: '#9D8CFF',
      },
    ),
  },
  {
    id: 'foxfire-default',
    name: 'Foxfire',
    width: 16,
    height: 16,
    backgroundColor: '#090815',
    pixels: pixelsFromRows(
      [
        '................',
        '...O........O...',
        '..ORO......ORO..',
        '..ORRO....ORRO..',
        '...ORR....RRO...',
        '....ORLLLLRO....',
        '....RLWLLWLR....',
        '...RLLWLLWLLR...',
        '...RLLLLLLLLR...',
        '....RLLWWLLR....',
        '.....RLLLLR.....',
        '......RLLR......',
        '......ORRO......',
        '.....O....O.....',
        '................',
        '................',
      ],
      {
        L: '#FFE2A8',
        O: '#FF9F1C',
        R: '#FF5E5B',
        W: '#FFFFFF',
      },
    ),
  },
  {
    id: 'mushroom-oracle-default',
    name: 'Mushroom Oracle',
    width: 16,
    height: 16,
    backgroundColor: '#08110D',
    pixels: pixelsFromRows(
      [
        '................',
        '......GGGG......',
        '....GGRRRRGG....',
        '...GRRWRRWRRG...',
        '..GRRRRRRRRRRG..',
        '..GRWGRRRRGWRG..',
        '...GRRRWWRRRG...',
        '....GGRTTRGG....',
        '......TTTT......',
        '.....TFFFFT.....',
        '.....TFFFFT.....',
        '....TTFFFFTT....',
        '...G..TFFT..G...',
        '..G...TFFT...G..',
        '......GGGG......',
        '................',
      ],
      {
        F: '#F7D6A5',
        G: '#70E000',
        R: '#C9184A',
        T: '#8D5A3B',
        W: '#FFFFFF',
      },
    ),
  },
  {
    id: 'storm-eye-default',
    name: 'Storm Eye',
    width: 16,
    height: 16,
    backgroundColor: '#07101E',
    pixels: pixelsFromRows(
      [
        '................',
        '................',
        '.......BB.......',
        '......BWWB......',
        '...B..BWWB..B...',
        '....B.BCCB.B....',
        '.....BBCBB......',
        '..BBBBCCCCBBBB..',
        '..BBBBCCCCBBBB..',
        '.....BBCBB......',
        '....B.BCCB.B....',
        '...B..BWWB..B...',
        '......BWWB......',
        '.......BB.......',
        '................',
        '................',
      ],
      {
        B: '#4D96FF',
        C: '#6FFFE9',
        W: '#EAFBFF',
      },
    ),
  },
] as const satisfies readonly Rune[];

export function getDefaultRuneById(runeId: string): Rune | undefined {
  return defaultRunes.find((rune) => rune.id === runeId);
}
